"""
Type stubs for the compiled C++ high-performance module `emotion_engine`.
"""

from typing import List

class Interaction:
    from_idx: int
    to_idx: int
    type: int

    def __init__(self) -> None: ...

class ArchetypeConfig:
    refusal_chance: float
    decay_rate: float
    temperature: float
    emotion_decay: float
    refusal_vulnerability: float
    emotion_coefficients: List[float]
    scoring_affinity: str
    scoring_utility: str
    scoring_trust: str

    def __init__(self) -> None: ...

class SimulationState:
    num_agents: int
    emotions: List[int]
    relations: List[int]
    sensitivities: List[float]
    emission_weights: List[float]
    agent_archetypes: List[int]
    archetype_configs: List[ArchetypeConfig]

class Engine:
    state: SimulationState
    last_day_interactions: List[Interaction]
    emotions: List[int]
    relations: List[int]

    def __init__(self, num_agents: int) -> None: ...
    def set_emotion(self, agent_idx: int, axis_idx: int, value: int) -> None: ...
    def set_relation(self, agent_idx: int, target_idx: int, u: int, a: int, t: int) -> None: ...
    def set_emission_weight(self, agent_idx: int, target_idx: int, weight: float) -> None: ...
    def set_archetype_config(
        self,
        idx: int,
        refusal_chance: float,
        decay_rate: float,
        temperature: float,
        emotion_decay: float,
        refusal_vulnerability: float,
        emotion_coefficients: List[float],
        scoring_affinity: str,
        scoring_utility: str,
        scoring_trust: str
    ) -> None: ...
    def set_agent_archetype(self, agent_idx: int, arch_idx: int) -> None: ...
    def influence_emotions(self) -> None: ...
    def apply_relation_decay(self) -> None: ...
    def react_to_relations(self) -> None: ...
    def react_to_emotions(self) -> None: ...
    def apply_emotion_decay(self) -> None: ...
    def calculate_priority_score(self, agent_idx: int, target_idx: int, context: str) -> float: ...
    def choose_target(self, agent_idx: int) -> int: ...
    def should_refuse(self, agent_idx: int, target_idx: int) -> bool: ...
    def process_interaction(self, agent_idx: int, target_idx: int, success: bool) -> None: ...
    def process_refusal(self, agent_idx: int, target_idx: int) -> None: ...
    def perform_daily_cycle(self, interactions_per_day: int) -> None: ...
    def seed(self, seed_val: int) -> None: ...
    def set_agent_names(self, names: List[str]) -> None: ...
    def save_states_csv(self, filename: str) -> None: ...
    def save_interactions_csv(self, filename: str) -> None: ...
